name: convertx
description: A powerful file converter built with Flutter and Rust.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_rust_bridge: ^2.0.0
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  file_picker: ^6.1.1
  desktop_drop: ^0.4.4
  path_provider: ^2.1.1
  open_file: ^3.3.2
  uuid: ^4.2.1
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  ffigen: ^11.0.0

flutter:
  uses-material-design: true
